stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd samset-salma-app
    - composer install
    - cp .env.example .env
    - php artisan key:generate

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "test still empty"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - ./vendor/bin/sail up
    - ./vendor/bin/sail artisan migrate:refresh --seed
